//! Implementation of a realtime structural stress simulation (6-DOF Frame Solver).

use bevy::{
    math::{DQuat, DVec3},
    prelude::*,
};

use faer::{
    prelude::*,
    sparse::{
        SparseColMat, Triplet,
        linalg::solvers::{Llt, SymbolicLlt},
    },
};

// =========================================================================
// CONFIGURATION (f64)
// =========================================================================

pub const CALIBRATION_FRAMES: usize = 0;

pub const DT: f64 = 0.01667;
pub const DOF_PER_NODE: usize = 6;

// Global Damping
pub const LIN_DAMPING: f64 = 0.999;
pub const ANG_DAMPING: f64 = 0.998;

// Internal Damping (Viscosity)
pub const INTERNAL_LIN_DAMPING: f64 = 1000.0;
pub const INTERNAL_ROT_DAMPING: f64 = 300.0;

pub const GRAVITY: DVec3 = DVec3::new(0.0, 0.0, 0.0);

// MASS
pub const NODE_MASS: f64 = 500.0;
pub const NODE_MOMENT_OF_INERTIA: f64 = 100.0;
// With f64, we can safely use a much larger Anchor Mass without precision loss
pub const ANCHOR_MASS: f64 = 1e12;

// STIFFNESS
// f64 allows us to be stiff without noise.
pub const JOINT_LIN_STIFFNESS: f64 = 2.0e7;
pub const JOINT_ROT_STIFFNESS: f64 = 9.0e8;

// =========================================================================
// DATA STRUCTURES
// =========================================================================

#[derive(Clone, Copy)]
pub struct MaterialProps {
    pub tension_mult: f64,
    pub compression_mult: f64,
    pub shear_mult: f64,
    pub bending_mult: f64,
    pub strength: f64,
}

pub const CONCRETE: MaterialProps = MaterialProps {
    // Calibrated to Impulse (Force * DT).
    strength: 1000.,
    tension_mult: 1.,
    compression_mult: 0.05,

    // LOWER THIS: Allow the horizontal beam to hold the weight via shear
    // without breaking immediately. We want the failure to happen at the Rotational support.
    shear_mult: 0.4,

    // INCREASE THIS: Make the vertical support very sensitive to the rotation
    // that will now be generated by the torque coupling.
    bending_mult: 0.4,
};

#[derive(Clone)]
pub struct PhysNode {
    pub fixed: bool,
    pub pos: DVec3,     // f64 (Local Space relative to Root)
    pub vel: DVec3,     // f64
    pub rot: DQuat,     // f64
    pub ang_vel: DVec3, // f64
}

#[derive(Clone)]
pub struct Connection {
    pub alive: bool,
    pub node_a: usize,
    pub node_b: usize,

    // Topology
    pub rest_len: f64,
    pub rest_local_rot: DQuat,
    pub local_axis: DVec3,

    pub last_stress_ratio: f32, // Keep f32 for rendering colors
    pub baseline_impulse: f64,
    pub material: MaterialProps,
}

pub struct Island {
    pub sleeping: bool,
    pub needs_refactor: bool,
    a: SparseColMat<usize, f64>,
    b: Col<f64>,
    symbolic: SymbolicLlt<usize>,
    llt: Llt<usize, f64>,
}

/// The "Kernel".
/// Stored on the Parent/Root entity (e.g., the Car, the Building).
/// Owns the memory for the solver.
#[derive(Component)]
pub struct StructuralSim {
    pub nodes: Vec<PhysNode>,
    pub connections: Vec<Connection>,
    pub island: Option<Island>,
    pub frame_count: usize,
    // MAPPING (The Bridge)
    // Index i corresponds to nodes[i].
    pub node_to_entity: Vec<Entity>,

    // PHYSICS MODE
    // If false (Static): We apply manual gravity to nodes (Visual Sag).
    // If true (Dynamic): We DO NOT apply gravity. Avian handles the Root's fall.
    pub is_dynamic: bool,
}

/// The "Handle".
/// Stored on every child entity (the individual mesh parts).
/// Allows O(1) lookups from a Collision Event to the specific Solver Node.
#[derive(Component)]
pub struct SimPart {
    pub root_entity: Entity,
    pub node_index: usize,
}

/// This is just a marker component for the visual entity (usually parent of collider) for ease of
/// navigation purposes.
#[derive(Component)]
pub struct VisualSimPart;

// =========================================================================
// PHYSICS IMPLEMENTATION (f64)
// =========================================================================

impl StructuralSim {
    pub fn new() -> Self {
        Self {
            nodes: Vec::new(),
            connections: Vec::new(),
            island: None,
            frame_count: 0,
            node_to_entity: Vec::new(),
            is_dynamic: false, // Default to Anchored/Static
        }
    }

    // Helper to accept Bevy's f32 types during setup, but store as f64
    pub fn add_node(
        &mut self,
        fixed: bool,
        pos: Vec3,
        vel: Vec3,
        rot: Quat,
        ang_vel: Vec3,
        entity: Entity,
    ) -> usize {
        self.nodes.push(PhysNode {
            fixed,
            pos: pos.as_dvec3(),
            vel: vel.as_dvec3(),
            rot: rot.as_dquat(),
            ang_vel: ang_vel.as_dvec3(),
        });
        self.node_to_entity.push(entity);
        self.nodes.len() - 1
    }

    pub fn add_conn(&mut self, node_a: usize, node_b: usize) {
        let pos_a = self.nodes[node_a].pos;
        let pos_b = self.nodes[node_b].pos;
        let diff = pos_b - pos_a;
        let rest_len = diff.length();

        let dir_world = if rest_len > 1e-9 {
            diff / rest_len
        } else {
            DVec3::Y
        };

        let rot_a = self.nodes[node_a].rot;
        let rot_b = self.nodes[node_b].rot;

        let rest_local_rot = rot_a.inverse() * rot_b;
        let local_axis = rot_a.inverse() * dir_world;

        self.connections.push(Connection {
            alive: true,
            node_a,
            node_b,
            rest_len,
            rest_local_rot,
            local_axis,
            last_stress_ratio: 0.,
            baseline_impulse: 0.,
            material: CONCRETE,
        });
    }

    pub fn generate_matrix_triplets(&self, dt: f64) -> (Vec<Triplet<usize, usize, f64>>, usize) {
        let n_nodes = self.nodes.len();
        let dof: usize = n_nodes * DOF_PER_NODE;
        let mut triplets: Vec<Triplet<usize, usize, f64>> = Vec::with_capacity(dof * 4);

        // 1. INERTIA
        for i in 0..n_nodes {
            let offset = i * DOF_PER_NODE;
            let n = &self.nodes[i];
            let (mass, inertia) = if n.fixed {
                (ANCHOR_MASS, ANCHOR_MASS)
            } else {
                (NODE_MASS, NODE_MOMENT_OF_INERTIA)
            };

            for r in 0..3 {
                triplets.push(Triplet::new(offset + r, offset + r, mass));
            }
            for r in 3..6 {
                triplets.push(Triplet::new(offset + r, offset + r, inertia));
            }
        }

        // 2. STIFFNESS (Decoupled Diagonal Blocks)
        let dt2 = dt * dt;
        let alpha_lin = (JOINT_LIN_STIFFNESS * dt2) + (INTERNAL_LIN_DAMPING * dt);
        let alpha_rot = (JOINT_ROT_STIFFNESS * dt2) + (INTERNAL_ROT_DAMPING * dt);

        for conn in &self.connections {
            if !conn.alive {
                continue;
            }
            let node_a = conn.node_a;
            let node_b = conn.node_b;

            if (self.nodes[node_b].pos - self.nodes[node_a].pos).length_squared() < 1e-12 {
                continue;
            }

            // Linear Block
            for r in 0..3 {
                let la = node_a * 6 + r;
                let lb = node_b * 6 + r;
                triplets.push(Triplet::new(la, la, alpha_lin));
                triplets.push(Triplet::new(lb, lb, alpha_lin));
                triplets.push(Triplet::new(la, lb, -alpha_lin));
                triplets.push(Triplet::new(lb, la, -alpha_lin));
            }

            // Angular Block
            for r in 0..3 {
                let aa = node_a * 6 + 3 + r;
                let ab = node_b * 6 + 3 + r;
                triplets.push(Triplet::new(aa, aa, alpha_rot));
                triplets.push(Triplet::new(ab, ab, alpha_rot));
                triplets.push(Triplet::new(aa, ab, -alpha_rot));
                triplets.push(Triplet::new(ab, aa, -alpha_rot));
            }
        }
        (triplets, dof)
    }

    pub fn create_island(&mut self) {
        let (triplets, dof) = self.generate_matrix_triplets(DT);

        let a = SparseColMat::<usize, f64>::try_new_from_triplets(dof, dof, &triplets)
            .expect("Failed to create matrix");
        let b = Col::zeros(dof);

        let symbolic =
            SymbolicLlt::try_new(a.symbolic(), faer::Side::Lower).expect("Symbolic failed");
        let llt = Llt::try_new_with_symbolic(symbolic.clone(), a.as_ref(), faer::Side::Lower)
            .expect("Indefinite matrix");

        self.island = Some(Island {
            sleeping: false,
            needs_refactor: false,
            a,
            b,
            symbolic,
            llt,
        });
    }

    pub fn update_stiffness_matrix(&mut self) {
        let (triplets, dof) = self.generate_matrix_triplets(DT);
        let Some(island) = self.island.as_mut() else {
            return;
        };
        island.a = SparseColMat::<usize, f64>::try_new_from_triplets(dof, dof, &triplets)
            .expect("Failed to update matrix");
    }

    pub fn check_breakage(&mut self) {
        let Some(island) = self.island.as_mut() else {
            return;
        };
        let is_calibrating = self.frame_count < CALIBRATION_FRAMES;
        let breakage_rotation_factor = 0.2;

        for i in 0..self.connections.len() {
            // 1. COPY PRIMITIVE DATA
            let (
                node_a_idx,
                node_b_idx,
                alive,
                mat,
                rest_len,
                local_axis,
                rest_local_rot,
                baseline_impulse,
            ) = {
                let c = &self.connections[i];
                (
                    c.node_a,
                    c.node_b,
                    c.alive,
                    c.material,
                    c.rest_len,
                    c.local_axis,
                    c.rest_local_rot,
                    c.baseline_impulse,
                )
            };

            if !alive {
                continue;
            }

            // 2. RECOVER FORCES
            let (p_a, v_a, r_a, w_a) = {
                let n = &self.nodes[node_a_idx];
                (n.pos, n.vel, n.rot, n.ang_vel)
            };
            let (p_b, v_b, r_b, w_b) = {
                let n = &self.nodes[node_b_idx];
                (n.pos, n.vel, n.rot, n.ang_vel)
            };

            // Linear Force
            let target_offset_world = r_a * local_axis * rest_len;
            let target_pos_b = p_a + target_offset_world;
            let pos_error = target_pos_b - p_b;

            let force_elastic = pos_error * JOINT_LIN_STIFFNESS;
            let rel_vel = v_b - v_a;
            let force_viscous = rel_vel * -INTERNAL_LIN_DAMPING;
            let fl = (force_elastic + force_viscous) * DT;

            // Angular Force
            let q_rel = r_a.inverse() * r_b;
            let q_err = q_rel * rest_local_rot.inverse();
            let (_, angle_sin) = q_err.to_axis_angle();

            let torque_elastic = JOINT_ROT_STIFFNESS * angle_sin;
            let rel_w = w_b - w_a;
            let torque_viscous = rel_w.length() * INTERNAL_ROT_DAMPING;
            let fa_mag = (torque_elastic + torque_viscous) * DT;

            // 3. DECOMPOSE STRESS (Using Socket Orientation for Frame)
            let dir = (r_a * local_axis).normalize();

            let normal_force = fl.dot(dir);
            let is_tension = normal_force < 0.0;

            let term_normal = if is_tension {
                normal_force.abs() * mat.tension_mult
            } else {
                normal_force.abs() * mat.compression_mult
            };

            let shear_vec = fl - (dir * normal_force);
            let shear_mag = shear_vec.length();
            let term_shear = shear_mag * mat.shear_mult;

            let induced_moment = shear_mag * (rest_len * 0.5);
            let term_bending = (fa_mag + induced_moment) * mat.bending_mult;

            let total_stress = term_normal + term_shear + term_bending;

            // 4. APPLY
            if is_calibrating {
                self.connections[i].baseline_impulse =
                    total_stress.max(self.connections[i].baseline_impulse);
            } else {
                let limit = baseline_impulse + mat.strength;
                let stress_excess = (total_stress - baseline_impulse).max(0.0);
                self.connections[i].last_stress_ratio = (stress_excess / mat.strength) as f32;

                if total_stress > limit {
                    self.connections[i].alive = false;
                    island.needs_refactor = true;

                    // Kinematic Compensation (Torque Injection)
                    if (term_bending + term_shear) > term_normal {
                        let lever_arm = dir * (rest_len * 0.5);
                        let torque_impulse = lever_arm.cross(shear_vec);
                        let rot_change = torque_impulse * breakage_rotation_factor;

                        if !self.nodes[node_a_idx].fixed {
                            self.nodes[node_a_idx].ang_vel += rot_change / NODE_MOMENT_OF_INERTIA;
                        }
                        if !self.nodes[node_b_idx].fixed {
                            self.nodes[node_b_idx].ang_vel -= rot_change / NODE_MOMENT_OF_INERTIA;
                        }
                    }
                }
            }
        }
    }

    pub fn solve_for_x(&mut self) {
        let Some(island) = self.island.as_mut() else {
            return;
        };

        self.frame_count += 1;
        if island.sleeping {
            return;
        }

        if island.needs_refactor {
            match SymbolicLlt::try_new(island.a.symbolic(), faer::Side::Lower) {
                Ok(new_sym) => {
                    island.symbolic = new_sym;
                    match Llt::try_new_with_symbolic(
                        island.symbolic.clone(),
                        island.a.as_ref(),
                        faer::Side::Lower,
                    ) {
                        Ok(new_llt) => island.llt = new_llt,
                        Err(_) => {
                            for n in &mut self.nodes {
                                n.vel = DVec3::ZERO;
                            }
                        }
                    }
                }
                Err(_) => {}
            }
            island.needs_refactor = false;
        }

        let n_nodes = self.nodes.len();
        island.b.fill(0.0);

        // 1. PREDICTION
        for (i, node) in self.nodes.iter_mut().enumerate() {
            if node.fixed {
                continue;
            }

            node.vel *= LIN_DAMPING;
            node.ang_vel *= ANG_DAMPING;

            let offset = i * DOF_PER_NODE;

            // [CRITICAL CHANGE]: Gravity Logic
            // If Dynamic: The Root is falling (Avian). Nodes are in freefall relative to Root. No Gravity.
            // If Static: The Root is fixed. Nodes must feel gravity to sag/break.
            let mut vel_pred = node.vel;

            if !self.is_dynamic {
                vel_pred += GRAVITY * DT;
            }

            let m = vel_pred * NODE_MASS;
            let am = node.ang_vel * NODE_MOMENT_OF_INERTIA;

            island.b[offset + 0] = m.x;
            island.b[offset + 1] = m.y;
            island.b[offset + 2] = m.z;
            island.b[offset + 3] = am.x;
            island.b[offset + 4] = am.y;
            island.b[offset + 5] = am.z;
        }

        // 2. RESTORING FORCES
        for conn in self.connections.iter() {
            if !conn.alive {
                continue;
            }

            let p_a = self.nodes[conn.node_a].pos;
            let p_b = self.nodes[conn.node_b].pos;
            let q_a = self.nodes[conn.node_a].rot;

            // Linear
            let target = p_a + q_a * conn.local_axis * conn.rest_len;
            let pos_error = target - p_b;
            let spring_impulse = pos_error * (JOINT_LIN_STIFFNESS * DT);

            // Angular
            let q_b = self.nodes[conn.node_b].rot;
            let q_err = (q_a.inverse() * q_b) * conn.rest_local_rot.inverse();
            let (axis, sin_a) = q_err.to_axis_angle();

            let ang_impulse = if sin_a.abs() > 1e-9 {
                q_a * axis * (-JOINT_ROT_STIFFNESS * sin_a * DT)
            } else {
                DVec3::ZERO
            };

            let ia = conn.node_a * 6;
            let ib = conn.node_b * 6;

            island.b[ib + 0] += spring_impulse.x;
            island.b[ib + 1] += spring_impulse.y;
            island.b[ib + 2] += spring_impulse.z;
            island.b[ia + 0] -= spring_impulse.x;
            island.b[ia + 1] -= spring_impulse.y;
            island.b[ia + 2] -= spring_impulse.z;

            island.b[ib + 3] += ang_impulse.x;
            island.b[ib + 4] += ang_impulse.y;
            island.b[ib + 5] += ang_impulse.z;
            island.b[ia + 3] -= ang_impulse.x;
            island.b[ia + 4] -= ang_impulse.y;
            island.b[ia + 5] -= ang_impulse.z;
        }

        let x = island.llt.solve(&island.b);

        for i in 0..n_nodes {
            if self.nodes[i].fixed {
                continue;
            }
            let o = i * 6;
            let mut v = DVec3::new(x[o], x[o + 1], x[o + 2]);
            let mut av = DVec3::new(x[o + 3], x[o + 4], x[o + 5]);

            let max_v = 200.0;
            if v.length_squared() > max_v * max_v {
                v = v.normalize() * max_v;
            }
            if av.length_squared() > max_v * max_v {
                av = av.normalize() * max_v;
            }

            self.nodes[i].vel = v;
            self.nodes[i].ang_vel = av;
            self.nodes[i].pos += v * DT;

            let q = self.nodes[i].rot;
            let dq = DQuat::from_xyzw(av.x, av.y, av.z, 0.0) * q * (0.5 * DT);
            self.nodes[i].rot = (q + dq).normalize();
        }
    }
}
