//! Implementation of a realtime structural stress simulation (6-DOF Frame Solver).
//! Refactored to use f64 (Double Precision) for solver stability.

#[allow(unused_imports)]
use bevy::{
    diagnostic::{FrameTimeDiagnosticsPlugin, LogDiagnosticsPlugin},
    math::{DQuat, DVec3}, // Import Double Precision types
    prelude::*,
};
use faer::{
    get_global_parallelism,
    prelude::*,
    sparse::{
        SparseColMat, Triplet,
        linalg::solvers::{Llt, SymbolicLlt},
    },
};

#[path = "../src/camera_controller.rs"]
mod camera_controller;
use camera_controller::*;

// =========================================================================
// CONFIGURATION (f64)
// =========================================================================

const CALIBRATION_FRAMES: usize = 0;

const DT: f64 = 0.01667;
const DOF_PER_NODE: usize = 6;

// Global Damping
const LIN_DAMPING: f64 = 0.999;
const ANG_DAMPING: f64 = 0.998;

// Internal Damping (Viscosity)
const INTERNAL_LIN_DAMPING: f64 = 1000.0;
const INTERNAL_ROT_DAMPING: f64 = 300.0;

const GRAVITY: DVec3 = DVec3::new(0.0, -9.81, 0.0);

// MASS
const NODE_MASS: f64 = 500.0;
const NODE_MOMENT_OF_INERTIA: f64 = 100.0;
// With f64, we can safely use a much larger Anchor Mass without precision loss
const ANCHOR_MASS: f64 = 1e12;

// STIFFNESS
// f64 allows us to be stiff without noise.
const JOINT_LIN_STIFFNESS: f64 = 2.0e7;
const JOINT_ROT_STIFFNESS: f64 = 9.0e8;

// STRENGTH
// Calibrated to Impulse (Force * DT).
const CONCRETE_STRENGTH: f64 = 1000.0;

// =========================================================================
// DATA STRUCTURES
// =========================================================================

#[derive(Clone, Copy)]
struct MaterialProps {
    tension_mult: f64,
    compression_mult: f64,
    shear_mult: f64,
    bending_mult: f64,
    strength: f64,
}

struct PhysNode {
    fixed: bool,
    pos: DVec3,     // f64
    vel: DVec3,     // f64
    rot: DQuat,     // f64
    ang_vel: DVec3, // f64
}

struct Connection {
    alive: bool,
    node_a: usize,
    node_b: usize,

    // Topology
    rest_len: f64,
    rest_local_rot: DQuat,
    local_axis: DVec3,

    last_stress_ratio: f32, // Keep f32 for rendering colors
    baseline_impulse: f64,
    material: MaterialProps,
}

struct Island {
    sleeping: bool,
    needs_refactor: bool,
    // Faer matrices now use f64
    a: SparseColMat<usize, f64>,
    b: Col<f64>,
    symbolic: SymbolicLlt<usize>,
    llt: Llt<usize, f64>,
}

#[derive(Resource)]
struct PhysicsWorld {
    nodes: Vec<PhysNode>,
    connections: Vec<Connection>,
    island: Option<Island>,
    frame_count: usize,
}

// =========================================================================
// PHYSICS IMPLEMENTATION (f64)
// =========================================================================

impl PhysicsWorld {
    fn new() -> Self {
        Self {
            nodes: Vec::new(),
            connections: Vec::new(),
            island: None,
            frame_count: 0,
        }
    }

    // Helper to accept Bevy's f32 types during setup, but store as f64
    fn add_node(&mut self, fixed: bool, pos: Vec3, vel: Vec3, rot: Quat, ang_vel: Vec3) -> usize {
        self.nodes.push(PhysNode {
            fixed,
            pos: pos.as_dvec3(),
            vel: vel.as_dvec3(),
            rot: rot.as_dquat(),
            ang_vel: ang_vel.as_dvec3(),
        });
        self.nodes.len() - 1
    }

    fn add_conn(&mut self, node_a: usize, node_b: usize) {
        let pos_a = self.nodes[node_a].pos;
        let pos_b = self.nodes[node_b].pos;
        let diff = pos_b - pos_a;
        let rest_len = diff.length();

        let dir_world = if rest_len > 1e-9 {
            diff / rest_len
        } else {
            DVec3::Y
        };

        let rot_a = self.nodes[node_a].rot;
        let rot_b = self.nodes[node_b].rot;

        let rest_local_rot = rot_a.inverse() * rot_b;
        let local_axis = rot_a.inverse() * dir_world;

        let concrete = MaterialProps {
            strength: CONCRETE_STRENGTH,
            tension_mult: 1.0,
            compression_mult: 0.05,

            // LOWER THIS: Allow the horizontal beam to hold the weight via shear
            // without breaking immediately. We want the failure to happen at the Rotational support.
            shear_mult: 0.4,

            // INCREASE THIS: Make the vertical support very sensitive to the rotation
            // that will now be generated by the torque coupling.
            bending_mult: 0.4,
        };

        self.connections.push(Connection {
            alive: true,
            node_a,
            node_b,
            rest_len,
            rest_local_rot,
            local_axis,
            last_stress_ratio: 0.0,
            baseline_impulse: 0.0,
            material: concrete,
        });
    }

    fn generate_matrix_triplets(&self, dt: f64) -> (Vec<Triplet<usize, usize, f64>>, usize) {
        let n_nodes = self.nodes.len();
        let dof: usize = n_nodes * DOF_PER_NODE;
        let mut triplets: Vec<Triplet<usize, usize, f64>> = Vec::with_capacity(dof * 4);

        // 1. INERTIA
        for i in 0..n_nodes {
            let offset = i * DOF_PER_NODE;
            let n = &self.nodes[i];
            let (mass, inertia) = if n.fixed {
                (ANCHOR_MASS, ANCHOR_MASS)
            } else {
                (NODE_MASS, NODE_MOMENT_OF_INERTIA)
            };

            for r in 0..3 {
                triplets.push(Triplet::new(offset + r, offset + r, mass));
            }
            for r in 3..6 {
                triplets.push(Triplet::new(offset + r, offset + r, inertia));
            }
        }

        // 2. STIFFNESS (Decoupled Diagonal Blocks)
        let dt2 = dt * dt;
        let alpha_lin = (JOINT_LIN_STIFFNESS * dt2) + (INTERNAL_LIN_DAMPING * dt);
        let alpha_rot = (JOINT_ROT_STIFFNESS * dt2) + (INTERNAL_ROT_DAMPING * dt);

        for conn in &self.connections {
            if !conn.alive {
                continue;
            }
            let node_a = conn.node_a;
            let node_b = conn.node_b;

            if (self.nodes[node_b].pos - self.nodes[node_a].pos).length_squared() < 1e-12 {
                continue;
            }

            // Linear Block
            for r in 0..3 {
                let la = node_a * 6 + r;
                let lb = node_b * 6 + r;
                triplets.push(Triplet::new(la, la, alpha_lin));
                triplets.push(Triplet::new(lb, lb, alpha_lin));
                triplets.push(Triplet::new(la, lb, -alpha_lin));
                triplets.push(Triplet::new(lb, la, -alpha_lin));
            }

            // Angular Block
            for r in 0..3 {
                let aa = node_a * 6 + 3 + r;
                let ab = node_b * 6 + 3 + r;
                triplets.push(Triplet::new(aa, aa, alpha_rot));
                triplets.push(Triplet::new(ab, ab, alpha_rot));
                triplets.push(Triplet::new(aa, ab, -alpha_rot));
                triplets.push(Triplet::new(ab, aa, -alpha_rot));
            }
        }
        (triplets, dof)
    }

    fn create_island(&mut self) {
        let (triplets, dof) = self.generate_matrix_triplets(DT);

        let a = SparseColMat::<usize, f64>::try_new_from_triplets(dof, dof, &triplets)
            .expect("Failed to create matrix");
        let b = Col::zeros(dof);

        let symbolic =
            SymbolicLlt::try_new(a.symbolic(), faer::Side::Lower).expect("Symbolic failed");
        let llt = Llt::try_new_with_symbolic(symbolic.clone(), a.as_ref(), faer::Side::Lower)
            .expect("Indefinite matrix");

        self.island = Some(Island {
            sleeping: false,
            needs_refactor: false,
            a,
            b,
            symbolic,
            llt,
        });
    }

    fn update_stiffness_matrix(&mut self) {
        let (triplets, dof) = self.generate_matrix_triplets(DT);
        let Some(island) = self.island.as_mut() else {
            return;
        };
        island.a = SparseColMat::<usize, f64>::try_new_from_triplets(dof, dof, &triplets)
            .expect("Failed to update matrix");
    }

    fn check_breakage(&mut self) {
        let Some(island) = self.island.as_mut() else {
            return;
        };
        let is_calibrating = self.frame_count < CALIBRATION_FRAMES;

        // Tuning: How much of the "Pent up" torque is converted to rotation when snapping?
        // 0.2 provides a nice tumble without exploding the simulation.
        let breakage_rotation_factor = 0.2;

        // Iterate by index to avoid borrowing `self.connections` while needing `self.nodes`
        for i in 0..self.connections.len() {
            // 1. EXTRACT CONNECTION DATA (Read-Only Copy)
            // We copy the primitive data we need to avoid holding a reference to self.connections
            let (
                node_a_idx,
                node_b_idx,
                alive,
                mat,
                rest_len,
                local_axis,
                rest_local_rot,
                baseline_impulse,
            ) = {
                let c = &self.connections[i];
                (
                    c.node_a,
                    c.node_b,
                    c.alive,
                    c.material,
                    c.rest_len,
                    c.local_axis,
                    c.rest_local_rot,
                    c.baseline_impulse,
                )
            };

            if !alive {
                continue;
            }

            // 2. RECOVER FORCES (Read-Only Access to Nodes)
            let (p_a, v_a, r_a, w_a) = {
                let n = &self.nodes[node_a_idx];
                (n.pos, n.vel, n.rot, n.ang_vel)
            };
            let (p_b, v_b, r_b, w_b) = {
                let n = &self.nodes[node_b_idx];
                (n.pos, n.vel, n.rot, n.ang_vel)
            };

            // -- Linear Force --
            // Target position of B relative to A based on A's rotation
            let target_offset_world = r_a * local_axis * rest_len;
            let target_pos_b = p_a + target_offset_world;
            let pos_error = target_pos_b - p_b;

            let force_elastic = pos_error * JOINT_LIN_STIFFNESS;
            let rel_vel = v_b - v_a;
            let force_viscous = rel_vel * -INTERNAL_LIN_DAMPING;
            let fl = (force_elastic + force_viscous) * DT; // Linear Impulse

            // -- Angular Force --
            let q_rel = r_a.inverse() * r_b;
            let q_err = q_rel * rest_local_rot.inverse();
            let (_, angle_sin) = q_err.to_axis_angle();

            let torque_elastic = JOINT_ROT_STIFFNESS * angle_sin;
            let rel_w = w_b - w_a;
            let torque_viscous = rel_w.length() * INTERNAL_ROT_DAMPING;
            let fa_mag = (torque_elastic + torque_viscous) * DT;

            // 3. DECOMPOSE STRESS
            // [SUGGESTED CHANGE]: Use the Socket Orientation (Node A) as the reference frame.
            // In a Decoupled Solver, the "Beam" is defined by the parent's rotation.
            // If we used (p_b - p_a), a beam hanging 90 deg down would register as Tension.
            // Using (r_a * axis) registers it as Shear (correct for Cantilever logic).
            let dir = (r_a * local_axis).normalize();

            let normal_force = fl.dot(dir);
            let is_tension = normal_force < 0.0;

            let term_normal = if is_tension {
                normal_force.abs() * mat.tension_mult
            } else {
                normal_force.abs() * mat.compression_mult
            };

            // Reject the normal component to get pure shear vector
            let shear_vec = fl - (dir * normal_force);
            let shear_mag = shear_vec.length();
            let term_shear = shear_mag * mat.shear_mult;

            // -- INDUCED BENDING MOMENT --
            // Logic: Shear Force * Lever Arm = Extra Torque
            let induced_moment = shear_mag * (rest_len * 0.5);
            let term_bending = (fa_mag + induced_moment) * mat.bending_mult;

            let total_stress = term_normal + term_shear + term_bending;

            // 4. APPLY RESULTS
            if is_calibrating {
                // During calibration, just raise the baseline
                self.connections[i].baseline_impulse =
                    total_stress.max(self.connections[i].baseline_impulse);
            } else {
                let limit = baseline_impulse + mat.strength;
                let stress_excess = (total_stress - baseline_impulse).max(0.0);

                // Update visualization ratio
                self.connections[i].last_stress_ratio = (stress_excess / mat.strength) as f32;

                if total_stress > limit {
                    // BREAK THE BOND
                    self.connections[i].alive = false;
                    island.needs_refactor = true;

                    // [THE FIX]: KINEMATIC COMPENSATION
                    // If we broke due to Shear/Bending, the solver suppressed the rotation.
                    // We must manually inject the angular momentum that "should" have existed.
                    if (term_bending + term_shear) > term_normal {
                        // Calculate Torque Vector: r x F
                        // r = Vector from A to center of beam
                        let lever_arm = dir * (rest_len * 0.5);

                        // F = The shear impulse vector calculated above
                        let torque_impulse = lever_arm.cross(shear_vec);

                        // Apply scaled rotation
                        let rot_change = torque_impulse * breakage_rotation_factor;

                        // Apply to A (Reaction: A feels torque as B snaps off)
                        if !self.nodes[node_a_idx].fixed {
                            self.nodes[node_a_idx].ang_vel += rot_change / NODE_MOMENT_OF_INERTIA;
                        }

                        // Apply to B (Action: B tumbles away)
                        // Opposite direction?
                        // If B shears DOWN relative to A, `shear_vec` on A (spring force) points UP (pulling A back).
                        // Therefore `shear_vec` on B points DOWN.
                        // The `shear_vec` variable above was derived from `fl`.
                        // `fl` = Force on A from B. (Spring pulls A towards B).
                        // So `shear_vec` is the force on A.
                        // Torque on A = r x F_on_A.

                        // Torque on B = r x F_on_B = r x (-F_on_A).
                        // Effectively, B should rotate opposite to A.
                        if !self.nodes[node_b_idx].fixed {
                            self.nodes[node_b_idx].ang_vel -= rot_change / NODE_MOMENT_OF_INERTIA;
                        }
                    }
                }
            }
        }
    }

    fn solve_for_x(&mut self) {
        let Some(island) = self.island.as_mut() else {
            return;
        };
        self.frame_count += 1;
        if island.sleeping {
            return;
        }

        if island.needs_refactor {
            match SymbolicLlt::try_new(island.a.symbolic(), faer::Side::Lower) {
                Ok(new_sym) => {
                    island.symbolic = new_sym;
                    match Llt::try_new_with_symbolic(
                        island.symbolic.clone(),
                        island.a.as_ref(),
                        faer::Side::Lower,
                    ) {
                        Ok(new_llt) => island.llt = new_llt,
                        Err(_) => {
                            for n in &mut self.nodes {
                                n.vel = DVec3::ZERO;
                            }
                        }
                    }
                }
                Err(_) => {}
            }
            island.needs_refactor = false;
        }

        let n_nodes = self.nodes.len();
        island.b.fill(0.0);

        // 1. PREDICTION
        for (i, node) in self.nodes.iter_mut().enumerate() {
            if node.fixed {
                continue;
            }
            node.vel *= LIN_DAMPING;
            node.ang_vel *= ANG_DAMPING;

            let offset = i * DOF_PER_NODE;
            let vel_pred = node.vel + GRAVITY * DT;
            let m = vel_pred * NODE_MASS;
            let am = node.ang_vel * NODE_MOMENT_OF_INERTIA;

            island.b[offset + 0] = m.x;
            island.b[offset + 1] = m.y;
            island.b[offset + 2] = m.z;
            island.b[offset + 3] = am.x;
            island.b[offset + 4] = am.y;
            island.b[offset + 5] = am.z;
        }

        // 2. RESTORING FORCES (Standard Implicit Spring)
        for conn in self.connections.iter() {
            if !conn.alive {
                continue;
            }
            let p_a = self.nodes[conn.node_a].pos;
            let p_b = self.nodes[conn.node_b].pos;
            let q_a = self.nodes[conn.node_a].rot;

            // A. Linear
            let target = p_a + q_a * conn.local_axis * conn.rest_len;
            let pos_error = target - p_b;
            let spring_impulse = pos_error * (JOINT_LIN_STIFFNESS * DT);

            // B. Angular
            let q_b = self.nodes[conn.node_b].rot;
            let q_err = (q_a.inverse() * q_b) * conn.rest_local_rot.inverse();
            let (axis, sin_a) = q_err.to_axis_angle();

            let ang_impulse = if sin_a.abs() > 1e-9 {
                q_a * axis * (-JOINT_ROT_STIFFNESS * sin_a * DT)
            } else {
                DVec3::ZERO
            };

            let ia = conn.node_a * 6;
            let ib = conn.node_b * 6;

            // Apply Linear
            island.b[ib + 0] += spring_impulse.x;
            island.b[ib + 1] += spring_impulse.y;
            island.b[ib + 2] += spring_impulse.z;
            island.b[ia + 0] -= spring_impulse.x;
            island.b[ia + 1] -= spring_impulse.y;
            island.b[ia + 2] -= spring_impulse.z;

            // Apply Angular
            island.b[ib + 3] += ang_impulse.x;
            island.b[ib + 4] += ang_impulse.y;
            island.b[ib + 5] += ang_impulse.z;
            island.b[ia + 3] -= ang_impulse.x;
            island.b[ia + 4] -= ang_impulse.y;
            island.b[ia + 5] -= ang_impulse.z;
        }

        let x = island.llt.solve(&island.b);

        for i in 0..n_nodes {
            if self.nodes[i].fixed {
                continue;
            }
            let o = i * 6;
            let mut v = DVec3::new(x[o], x[o + 1], x[o + 2]);
            let mut av = DVec3::new(x[o + 3], x[o + 4], x[o + 5]);

            // f64 Caps
            let max_v = 200.0;
            if v.length_squared() > max_v * max_v {
                v = v.normalize() * max_v;
            }
            if av.length_squared() > max_v * max_v {
                av = av.normalize() * max_v;
            }

            self.nodes[i].vel = v;
            self.nodes[i].ang_vel = av;
            self.nodes[i].pos += v * DT;

            let q = self.nodes[i].rot;
            let dq = DQuat::from_xyzw(av.x, av.y, av.z, 0.0) * q * (0.5 * DT);
            self.nodes[i].rot = (q + dq).normalize();
        }
    }
}

// =========================================================================
// SYSTEMS
// =========================================================================

fn main() {
    App::new()
        .add_plugins((
            DefaultPlugins,
            LogDiagnosticsPlugin::default(),
            CameraControllerPlugin,
        ))
        .insert_resource(PhysicsWorld::new())
        .insert_resource(SpaceRemoveableNodes::default())
        .add_systems(Startup, (print_faer_info, setup_doorframe, setup))
        .add_systems(FixedUpdate, solve_system)
        .add_systems(Update, (render, input_force, camera_movement))
        .insert_resource(Time::<Fixed>::from_seconds(DT)) // Bevy accepts f64 for Time
        .run();
}

fn print_faer_info() {
    match get_global_parallelism() {
        Par::Seq => {
            info!("faer runs sequentially.");
        }
        Par::Rayon(nz) => {
            info!("faer runs in parallel with {} threads.", nz);
        }
    }
}

#[allow(dead_code)]
fn setup_sqare_tower(mut sim: ResMut<PhysicsWorld>) {
    let w = 6;
    let d = 6;
    let h = 20;

    // Spacing between nodes
    let s = 4.0;

    info!("Building a tower with {} nodes...", w * d * h);

    // Store indices in a 3D grid for easy connection
    let mut grid = vec![vec![vec![0; d]; w]; h];

    // 1. Create Nodes
    for y in 0..h {
        for x in 0..w {
            for z in 0..d {
                // Center the tower on X and Z, start Y at 0
                let pos = vec3(
                    (x as f32 - (w as f32 - 1.0) / 2.0) * s,
                    y as f32 * s,
                    (z as f32 - (d as f32 - 1.0) / 2.0) * s,
                );

                // Fix the bottom layer to the ground
                let fixed = y == 0;

                let idx = sim.add_node(fixed, pos, Vec3::ZERO, Quat::IDENTITY, Vec3::ZERO);
                grid[y][x][z] = idx;
            }
        }
    }

    // 2. Create Connections (Structural Frame)
    for y in 0..h {
        for x in 0..w {
            for z in 0..d {
                let me = grid[y][x][z];

                // Vertical Column (Up)
                if y + 1 < h {
                    sim.add_conn(me, grid[y + 1][x][z]);
                }

                // Horizontal Beam (Right/X)
                if x + 1 < w {
                    sim.add_conn(me, grid[y][x + 1][z]);
                }

                // Horizontal Beam (Forward/Z)
                if z + 1 < d {
                    sim.add_conn(me, grid[y][x][z + 1]);
                }
            }
        }
    }

    sim.create_island();
}

#[derive(Resource, Default)]
struct SpaceRemoveableNodes(Vec<usize>);

fn setup_doorframe(
    mut sim: ResMut<PhysicsWorld>,
    mut removable_nodes: ResMut<SpaceRemoveableNodes>,
) {
    // =========================================================================
    // CONTROLS
    // =========================================================================
    const SUPPORT_HEIGHT: f32 = 3.0;
    const CHAIN_LENGTH: f32 = 4.0; // Defines the width of the doorframe

    // Resolution of the simulation (distance between nodes)
    const SPACING: f32 = 1.0;

    info!(
        "Generating Doorframe: Height={}, Width={}",
        SUPPORT_HEIGHT, CHAIN_LENGTH
    );

    // =========================================================================
    // BUILD
    // =========================================================================

    let half_width = CHAIN_LENGTH / 2.0;
    let left_x = -half_width;
    let right_x = half_width;
    let top_y = SUPPORT_HEIGHT;

    // Helper to build a vertical pillar
    // Returns the index of the top node
    let mut build_pillar = |x_pos: f32| -> usize {
        let mut prev_node = None;
        let steps = (SUPPORT_HEIGHT / SPACING).ceil() as usize;

        for i in 0..=steps {
            let t = i as f32 / steps as f32;
            let y = t * SUPPORT_HEIGHT;

            // Fix the bottom node (i=0)
            let fixed = i == 0;

            let node_idx = sim.add_node(
                fixed,
                Vec3::new(x_pos, y, 0.0),
                Vec3::ZERO,
                Quat::IDENTITY,
                Vec3::ZERO,
            );

            if let Some(prev) = prev_node {
                sim.add_conn(prev, node_idx);
            }
            prev_node = Some(node_idx);
        }
        prev_node.unwrap()
    };

    // 1. Build Left and Right Supports
    let top_left_idx = build_pillar(left_x);
    let top_right_idx = build_pillar(right_x);

    // 2. Build Top Beam ("The Chain")
    // We connect the existing top-left node to the existing top-right node
    // by filling the space in between.

    let beam_steps = (CHAIN_LENGTH / SPACING).ceil() as usize;
    let mut prev_node = top_left_idx;

    // Iterate from 1 to steps-1 (skipping 0 and max, because those are the pillars)
    for i in 1..beam_steps {
        let t = i as f32 / beam_steps as f32;
        let x = left_x + (right_x - left_x) * t;

        let node_idx = sim.add_node(
            false,
            Vec3::new(x, top_y, 0.0),
            Vec3::ZERO,
            Quat::IDENTITY,
            Vec3::ZERO,
        );

        sim.add_conn(prev_node, node_idx);
        prev_node = node_idx;
    }

    removable_nodes.0.push(0);

    // Connect the last piece of the chain to the Right Support
    sim.add_conn(prev_node, top_right_idx);

    // Initialize Solver
    sim.create_island();
}

// Setup functions must now handle Vector casting (Bevy Vec3 -> DVec3 happens inside add_node)
#[allow(dead_code)]
fn setup_tshape(mut sim: ResMut<PhysicsWorld>) {
    // Node 0: Base
    let n0 = sim.add_node(
        true,
        vec3(0.0, 0.0, 0.0),
        Vec3::ZERO,
        Quat::IDENTITY,
        Vec3::ZERO,
    );
    // Node 1: Pillar Top
    let n1 = sim.add_node(
        false,
        vec3(0.0, 6.0, 0.0),
        Vec3::ZERO,
        Quat::IDENTITY,
        Vec3::ZERO,
    );
    // Arms
    let n2 = sim.add_node(
        false,
        vec3(-4.0, 6.0, 0.0),
        Vec3::ZERO,
        Quat::IDENTITY,
        Vec3::ZERO,
    );
    let n3 = sim.add_node(
        false,
        vec3(4.0, 6.0, 0.0),
        Vec3::ZERO,
        Quat::IDENTITY,
        Vec3::ZERO,
    );

    sim.add_conn(n0, n1);
    sim.add_conn(n1, n2);
    sim.add_conn(n1, n3);

    // Add heavy chain to test cantilever shear
    let mut prev = n3;
    for i in 2..20 {
        let new = sim.add_node(
            false,
            vec3(i as f32 * 4.0, 6.0, 0.0),
            Vec3::ZERO,
            Quat::IDENTITY,
            Vec3::ZERO,
        );
        sim.add_conn(prev, new);
        prev = new;
    }

    sim.create_island();
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    commands.spawn((
        Camera3d::default(),
        Transform::from_xyz(20.0, 15.0, 30.0).looking_at(Vec3::new(5.0, 5.0, 0.0), Vec3::Y),
        CameraMoveSpeed(15.0),
        CameraMoveSpeedMult(5.0),
        CameraController::default(),
    ));

    commands.spawn((
        Mesh3d(meshes.add(Cuboid::new(50.0, 1.0, 50.0))),
        MeshMaterial3d(materials.add(StandardMaterial::from_color(Color::srgb(0.2, 0.2, 0.2)))),
        Transform::from_xyz(0.0, -2.0, 0.0),
    ));

    commands.spawn((PointLight::default(), Transform::from_xyz(0.0, 10.0, 10.0)));
}

fn solve_system(mut sim: ResMut<PhysicsWorld>) {
    sim.solve_for_x();
    sim.check_breakage();
    if sim.island.as_ref().unwrap().needs_refactor {
        sim.update_stiffness_matrix();
    }
}

fn input_force(
    keys: Res<ButtonInput<KeyCode>>,
    mouse: Res<ButtonInput<MouseButton>>,
    camera: Single<&GlobalTransform, With<Camera>>,
    mut sim: ResMut<PhysicsWorld>,
    mut gizmos: Gizmos,
    mut removable_nodes: ResMut<SpaceRemoveableNodes>,
) {
    if keys.just_pressed(KeyCode::Space) {
        for idx in removable_nodes.0.iter() {
            sim.nodes[*idx].fixed = false;
        }

        removable_nodes.0.clear();

        sim.update_stiffness_matrix();

        if let Some(island) = sim.island.as_mut() {
            island.needs_refactor = true;
        }
    }

    let tform = *camera;
    let pole_len = tform.forward() * 8.0;
    let center_f32 = Vec3::new(
        tform.translation().x + pole_len.x,
        tform.translation().y + pole_len.y,
        tform.translation().z + pole_len.z,
    );
    let center = center_f32.as_dvec3(); // Convert to f64 for physics

    gizmos.sphere(center_f32, 0.1, Color::WHITE);

    if mouse.just_pressed(MouseButton::Left) {
        let impulse = 500_000.0;
        for n in &mut sim.nodes {
            let diff = n.pos - center;
            let dist = diff.length();
            if dist < 40.0 {
                let dist_clamped = dist.max(1.0);
                let force_mag = (impulse / NODE_MASS) / (dist_clamped * dist_clamped);
                n.vel += diff.normalize() * force_mag * DT;
            }
        }
    }
}

fn render(mut gizmos: Gizmos, sim: Res<PhysicsWorld>) {
    for conn in &sim.connections {
        if !conn.alive {
            continue;
        }
        // Downcast f64 -> f32 for rendering
        let p_a = sim.nodes[conn.node_a].pos.as_vec3();
        let p_b = sim.nodes[conn.node_b].pos.as_vec3();
        let ratio = conn.last_stress_ratio;
        let color = if ratio > 1.0 {
            Color::WHITE
        } else {
            Color::srgb(ratio, 1.0 - ratio, 0.0)
        };
        gizmos.line(p_a, p_b, color);
    }
    for node in &sim.nodes {
        let pos = node.pos.as_vec3();
        let color = if node.fixed {
            Color::WHITE
        } else {
            Color::srgb(0.0, 0.0, 1.0)
        };
        gizmos.cuboid(
            Transform::from_translation(pos).with_scale(Vec3::splat(0.3)),
            color,
        );

        // Rotation axis
        let axis = (node.rot * DVec3::X).as_vec3() * 0.1;
        gizmos.line(pos, pos + axis, Color::srgb(1.0, 0.0, 0.0));
    }
}
